import subprocess
import time
import sys
import os
import uuid
import platform
import playlist_manager
import proxy_manager
from config_manager import get_quality_settings

def get_font_path():
    """
    Determines a valid font path based on the operating system.
    Returns None if no obvious font is found (FFmpeg might use default or fail).
    """
    system = platform.system()

    if system == 'Windows':
        # Common Windows font
        font_candidates = [
            r"C:\Windows\Fonts\arial.ttf",
            r"C:\Windows\Fonts\seguiemj.ttf", # Good for emojis if needed
            r"C:\Windows\Fonts\tahoma.ttf"
        ]
    elif system == 'Linux':
        font_candidates = [
            "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/usr/share/fonts/TTF/DejaVuSans.ttf",
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
            "/usr/share/fonts/truetype/freefont/FreeSans.ttf"
        ]
    else:
        # MacOS or other
        font_candidates = [
            "/Library/Fonts/Arial.ttf",
            "/System/Library/Fonts/Helvetica.ttc"
        ]

    for font in font_candidates:
        if os.path.exists(font):
            # FFmpeg requires paths to be escaped properly in filter strings.
            # On Windows, backslashes need double escaping or forward slashes.
            # Using forward slashes is safest for FFmpeg filters.
            clean_path = font.replace('\\', '/')

            return clean_path

    return None

def build_ffmpeg_command(config, playlist_mode=False):
    """
    Membuat list argumen perintah FFmpeg berdasarkan konfigurasi.
    """
    stream_key = config.get('stream_key')
    video_path = config.get('video_path')
    quality = config.get('quality', 'medium')

    if not stream_key or not video_path:
        raise ValueError("Stream Key atau Path Video belum diatur.")

    if not os.path.exists(video_path):
        raise FileNotFoundError(f"File video tidak ditemukan: {video_path}")

    settings = get_quality_settings(quality)

    # URL Server RTMP YouTube
    rtmp_url = f"rtmp://a.rtmp.youtube.com/live2/{stream_key}"

    # Generate random hash string for overlay
    random_hash = uuid.uuid4().hex[:8].upper()

    # Get Font Path
    font_path = get_font_path()

    # Construct Filter Chain
    # 1. Timer: Bottom-Left
    # 2. Random Hash: Top-Right

    # Helper for drawing text
    def make_drawtext(text, x, y, color='white'):
        # If font_path is found, use it. Otherwise, rely on FFmpeg internal/default.
        font_opt = f"fontfile='{font_path}':" if font_path else ""
        return (
            f"drawtext={font_opt}"
            f"text='{text}':"
            f"x={x}:y={y}:"
            f"fontsize=24:fontcolor={color}:"
            "box=1:boxcolor=black@0.5"
        )

    # Timer Filter (x=10, y=10 is top left, wait user asked for TOP corner)
    # The prompt said: "tampilan jam yang menghitung waktu ... letakan di pojok atas agar tidak menggangu tampilan video"
    # I will put Timer at Top-Left (10,10) and Hash at Top-Right (w-tw-10, 10)
    timer_filter = make_drawtext(r'%{pts:hms}', '10', '10')
    hash_filter = make_drawtext(f'ID: {random_hash}', 'w-tw-10', '10', 'yellow')

    filters = f"{timer_filter},{hash_filter}"

    command = ['ffmpeg', '-re']

    # Input handling
    if playlist_mode:
        # Note: playlist_mode means video_path is a text file generated by playlist_manager
        command.extend(['-f', 'concat', '-safe', '0', '-i', video_path])
    else:
        # Single file loop
        command.extend(['-stream_loop', '-1', '-i', video_path])

    command.extend([
        '-vf', filters,         # Video filters (overlay)
        '-c:v', 'libx264',      # Video codec
        '-preset', settings['preset'],
        '-b:v', settings['maxrate'],
        '-maxrate', settings['maxrate'],
        '-bufsize', settings['bufsize'],
        '-pix_fmt', 'yuv420p',
        '-g', '50',             # GOP size
        '-c:a', 'aac',          # Audio codec
        '-b:a', '128k',
        '-ar', '44100',
        '-f', 'flv',            # Output format
        rtmp_url
    ])

    return command

def mask_command(command):
    """
    Menyembunyikan stream key dari log command.
    """
    masked = []
    for arg in command:
        if "rtmp://" in arg:
            # Mask stream key (part after live2/)
            parts = arg.split("live2/")
            if len(parts) > 1:
                masked.append(parts[0] + "live2/*****")
            else:
                masked.append(arg)
        else:
            masked.append(arg)
    return " ".join(masked)

def start_stream(config):
    """
    Menjalankan proses streaming dengan fitur auto-restart.
    """
    print("\n[INFO] Menyiapkan streaming...")

    retry_count = 0

    # Check input type
    original_video_path = config.get('video_path')
    is_directory = os.path.isdir(original_video_path)

    while True:
        try:
            # 1. Setup Proxy
            print("\n[INFO] Mengambil Proxy...")
            proxy_url = proxy_manager.get_random_proxy()
            if proxy_url:
                print(f"[INFO] Proxy Aktif: {proxy_url}")
                # Set environment variables for FFmpeg to pick up
                os.environ["HTTP_PROXY"] = proxy_url
                os.environ["HTTPS_PROXY"] = proxy_url
                os.environ["http_proxy"] = proxy_url
                os.environ["https_proxy"] = proxy_url
            else:
                print("[WARN] Gagal mengambil proxy, menggunakan koneksi langsung.")
                # Clear proxy env vars if any
                os.environ.pop("HTTP_PROXY", None)
                os.environ.pop("HTTPS_PROXY", None)
                os.environ.pop("http_proxy", None)
                os.environ.pop("https_proxy", None)

            # 2. Setup Input (Playlist or Single File)
            current_input_path = original_video_path
            playlist_mode = False

            if is_directory:
                print("[INFO] Membuat Playlist Acak dari Folder...")
                playlist_path = playlist_manager.generate_playlist(original_video_path)
                if playlist_path:
                    current_input_path = playlist_path
                    playlist_mode = True
                    print(f"[INFO] Playlist dibuat: {playlist_path}")
                else:
                    print("[ERROR] Gagal membuat playlist (mungkin folder kosong?). Berhenti.")
                    return

            # Update config temporary for command builder
            temp_config = config.copy()
            temp_config['video_path'] = current_input_path

            command = build_ffmpeg_command(temp_config, playlist_mode=playlist_mode)

            print(f"\n[INFO] Memulai Stream ke YouTube... (Tekan Ctrl+C untuk berhenti)")
            if is_directory:
                print(f"[INFO] Folder Sumber: {original_video_path}")
            else:
                print(f"[INFO] File Sumber: {original_video_path}")
            print(f"[INFO] Kualitas: {config['quality']}")

            # Print command for debugging
            print(f"[DEBUG] Command: {mask_command(command)}")

            # Jalankan FFmpeg
            process = subprocess.Popen(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                universal_newlines=True
            )

            try:
                # Loop untuk membaca output
                while True:
                    output = process.stderr.readline()
                    if output == '' and process.poll() is not None:
                        break
                    if output:
                        output = output.strip()
                        # Only filter specific status lines to keep clean UI
                        # But print everything else to debug errors
                        if "time=" in output and "bitrate=" in output:
                            sys.stdout.write(f"\r[STREAMING] {output.split('bitrate=')[0]}...")
                            sys.stdout.flush()
                        elif "frame=" in output:
                            # Skip frame= updates if they don't have time (rare)
                            pass
                        else:
                            # Print errors/warnings/info from FFmpeg
                            print(f"\n[FFMPEG] {output}")
            except KeyboardInterrupt:
                print("\n\n[STOP] Menghentikan streaming...")
                process.kill()
                return

            return_code = process.poll()

            if return_code != 0:
                print(f"\n[WARN] FFmpeg berhenti dengan kode: {return_code}")
                print("[INFO] Mencoba menyambungkan kembali dalam 5 detik...")
                time.sleep(5)
                retry_count += 1
            else:
                print("\n[INFO] FFmpeg berhenti normal.")
                # If using playlist, we might want to loop (restart loop will re-shuffle)
                print("[INFO] Restarting stream loop...")
                time.sleep(1)

        except FileNotFoundError:
            print("\n[ERROR] FFmpeg tidak ditemukan. Pastikan FFmpeg sudah terinstall dan masuk ke PATH.")
            return
        except KeyboardInterrupt:
            print("\n[STOP] Berhenti atas permintaan pengguna.")
            return
        except Exception as e:
            print(f"\n[ERROR] Terjadi kesalahan tak terduga: {e}")
            import traceback
            traceback.print_exc()
            time.sleep(5)
